dataset:
  event_type: click
  precomputed: False
  click:
    negative_sampling_ratio: 0.15
    features: [
      candidates, candidate_scores,
      session_candidate_count, session_candidate_score_mean, session_candidate_score_std,
      session_candidate_score_min, session_candidate_score_max,
      session_candidate_occurrence_count,
      aid_type_mean, aid_hour_mean, aid_hour_std, aid_day_of_week_mean, aid_day_of_week_std,
      aid_ts_ratio, aid_session_recency_weight_mean,
      aid_is_session_start_mean, aid_is_session_end_mean,
      aid_click_ratio, aid_cart_ratio, aid_order_ratio,
      aid_click_is_session_end_mean, aid_cart_is_session_end_mean, aid_order_is_session_end_mean,
      aid_click_last_week_occurrence_ratio, aid_cart_last_week_occurrence_ratio, aid_order_last_week_occurrence_ratio,
      session_count, session_aid_nunique, session_ts_ratio, session_type_mean,
      session_hour_mean, session_day_of_week_mean, session_day_of_week_last,
    ]
    target: candidate_labels
    categorical_features: []
  cart:
    negative_sampling_ratio: 0.15
    features: [
      candidates, candidate_scores,
      aid_count, aid_session_nunique, aid_type_mean,
      aid_hour_mean, aid_hour_std, aid_day_of_week_mean, aid_day_of_week_std, aid_ts_ratio,
      aid_click_count, aid_cart_count, aid_order_count,
      click_last_week_occurrence_ratio, cart_last_week_occurrence_ratio, order_last_week_occurrence_ratio,
      session_count, session_type_mean, session_hour_mean, session_day_of_week_mean,
      session_click_aid_nunique, session_cart_aid_nunique, session_order_aid_nunique,
    ]
    target: candidate_labels
    categorical_features: []
  order:
    negative_sampling_ratio: 0.15
    features: [
      candidates, candidate_scores,
      aid_count, aid_session_nunique, aid_type_mean,
      aid_hour_mean, aid_hour_std, aid_day_of_week_mean, aid_day_of_week_std, aid_ts_ratio,
      aid_click_count, aid_cart_count, aid_order_count,
      click_last_week_occurrence_ratio, cart_last_week_occurrence_ratio, order_last_week_occurrence_ratio,
      session_count, session_type_mean, session_hour_mean, session_day_of_week_mean,
      session_click_aid_nunique, session_cart_aid_nunique, session_order_aid_nunique
    ]
    target: candidate_labels
    categorical_features: []

model:
  click:
    num_leaves: 128
    learning_rate: 0.05
    bagging_fraction: 0.8
    bagging_freq: 1
    feature_fraction: 0.9
    feature_fraction_bynode: 0.9
    min_data_in_leaf: 2000
    min_gain_to_split: 0.00001
    lambda_l1: 0.
    lambda_l2: 0.
    max_bin: 255
    max_depth: -1
    boost_from_average: True
    objective: lambdarank
    metric: mean_average_precision
    eval_at: [20, 50, 100]
    seed: 42
    feature_fraction_seed: 42
    bagging_seed: 42
    drop_seed: 42
    data_random_seed: 42
    boosting_type: gbdt
    verbose: 1
    n_jobs: -1
  cart:
    num_leaves: 64
    learning_rate: 0.05
    bagging_fraction: 0.7
    bagging_freq: 1
    feature_fraction: 0.9
    feature_fraction_bynode: 0.9
    min_data_in_leaf: 200
    min_gain_to_split: 0.00001
    lambda_l1: 0.
    lambda_l2: 0.
    max_bin: 255
    max_depth: -1
    boost_from_average: True
    objective: lambdarank
    metric: mean_average_precision
    eval_at: [ 20, 50, 100 ]
    seed: 42
    feature_fraction_seed: 42
    bagging_seed: 42
    drop_seed: 42
    data_random_seed: 42
    boosting_type: gbdt
    verbose: 1
    n_jobs: -1
  order:
    num_leaves: 64
    learning_rate: 0.05
    bagging_fraction: 0.7
    bagging_freq: 1
    feature_fraction: 0.9
    feature_fraction_bynode: 0.9
    min_data_in_leaf: 200
    min_gain_to_split: 0.00001
    lambda_l1: 0.
    lambda_l2: 0.
    max_bin: 255
    max_depth: -1
    boost_from_average: True
    objective: lambdarank
    metric: mean_average_precision
    eval_at: [ 20, 50, 100 ]
    seed: 42
    feature_fraction_seed: 42
    bagging_seed: 42
    drop_seed: 42
    data_random_seed: 42
    boosting_type: gbdt
    verbose: 1
    n_jobs: -1

fit:
  boosting_rounds: 500
  log_evaluation: 100

persistence:
  save_models: True
  visualize_feature_importance: True