dataset:
  event_type: click
  click:
    negative_sampling_ratio: 0.30
    features: [
      candidate_scores,
      session_candidate_occurrence_count, session_candidate_click_occurrence_count,
      session_candidate_cart_occurrence_count, session_candidate_order_occurrence_count,
      aid_candidate_score_mean, aid_candidate_score_std, aid_candidate_score_max,
      aid_session_candidate_occurrence_count_mean, aid_session_candidate_occurrence_count_sum, aid_session_candidate_occurrence_count_max,
      aid_type_mean, aid_hour_mean, aid_hour_std, aid_day_of_week_mean, aid_day_of_week_std,
      aid_ts_ratio, aid_is_session_start_mean, aid_is_session_end_mean,
      aid_count_rank_pct, aid_day_of_year_nunique_rank_pct,
      aid_click_count_rank_pct, aid_cart_count_rank_pct, aid_order_count_rank_pct,
      aid_click_session_nunique_rank_pct, aid_cart_session_nunique_rank_pct, aid_order_session_nunique_rank_pct,
      aid_click_day_of_year_nunique_rank_pct, aid_cart_day_of_year_nunique_rank_pct, aid_order_day_of_year_nunique_rank_pct,
      aid_last_week_count_rank_pct, aid_last_week_ts_ratio, aid_last_week_day_of_week_mean,
      aid_click_last_week_occurrence_ratio, aid_cart_last_week_occurrence_ratio, aid_order_last_week_occurrence_ratio,
      aid_click_last_week_occurrence_pct_change, aid_cart_last_week_occurrence_pct_change, aid_order_last_week_occurrence_pct_change,
      session_count, session_aid_nunique, session_aid_last, session_type_last, session_day_of_week_last,
      session_aid_count_mean, session_aid_count_min, session_aid_count_max, session_aid_count_last,
      session_aid_type_mean_mean, session_aid_hour_mean_mean,
      session_aid_session_nunique_rank_pct_mean, session_aid_session_nunique_rank_pct_last,
      session_aid_last_week_session_nunique_mean, session_aid_last_week_session_nunique_last
    ]
    target: candidate_labels
    categorical_features: []
  cart:
    negative_sampling_ratio: 0.30
    features: [
      candidate_scores,
      session_candidate_occurrence_count, session_candidate_click_occurrence_count,
      session_candidate_cart_occurrence_count, session_candidate_order_occurrence_count,
      aid_candidate_score_mean, aid_candidate_score_std, aid_candidate_score_max,
      aid_session_candidate_occurrence_count_mean, aid_session_candidate_occurrence_count_sum, aid_session_candidate_occurrence_count_max,
      aid_type_mean, aid_hour_mean, aid_hour_std, aid_day_of_week_mean, aid_day_of_week_std,
      aid_ts_ratio, aid_is_session_start_mean, aid_is_session_end_mean,
      aid_count_rank_pct, aid_day_of_year_nunique_rank_pct,
      aid_click_count_rank_pct, aid_cart_count_rank_pct, aid_order_count_rank_pct,
      aid_click_session_nunique_rank_pct, aid_cart_session_nunique_rank_pct, aid_order_session_nunique_rank_pct,
      aid_click_day_of_year_nunique_rank_pct, aid_cart_day_of_year_nunique_rank_pct, aid_order_day_of_year_nunique_rank_pct,
      aid_last_week_count_rank_pct, aid_last_week_ts_ratio, aid_last_week_day_of_week_mean,
      aid_click_last_week_occurrence_ratio, aid_cart_last_week_occurrence_ratio, aid_order_last_week_occurrence_ratio,
      aid_click_last_week_occurrence_pct_change, aid_cart_last_week_occurrence_pct_change, aid_order_last_week_occurrence_pct_change,
      session_count, session_aid_nunique, session_aid_last, session_type_last, session_day_of_week_last,
      session_aid_count_mean, session_aid_count_min, session_aid_count_max, session_aid_count_last,
      session_aid_type_mean_mean, session_aid_hour_mean_mean,
      session_aid_session_nunique_rank_pct_mean, session_aid_session_nunique_rank_pct_last,
      session_aid_last_week_session_nunique_mean, session_aid_last_week_session_nunique_last
    ]
    target: candidate_labels
    categorical_features: []
  order:
    negative_sampling_ratio: 0.30
    features: [
      candidate_scores,
      session_candidate_occurrence_count, session_candidate_click_occurrence_count,
      session_candidate_cart_occurrence_count, session_candidate_order_occurrence_count,
      aid_candidate_score_mean, aid_candidate_score_std, aid_candidate_score_max,
      aid_session_candidate_occurrence_count_mean, aid_session_candidate_occurrence_count_sum, aid_session_candidate_occurrence_count_max,
      aid_type_mean, aid_hour_mean, aid_hour_std, aid_day_of_week_mean, aid_day_of_week_std,
      aid_ts_ratio, aid_is_session_start_mean, aid_is_session_end_mean,
      aid_count_rank_pct, aid_day_of_year_nunique_rank_pct,
      aid_click_count_rank_pct, aid_cart_count_rank_pct, aid_order_count_rank_pct,
      aid_click_session_nunique_rank_pct, aid_cart_session_nunique_rank_pct, aid_order_session_nunique_rank_pct,
      aid_click_day_of_year_nunique_rank_pct, aid_cart_day_of_year_nunique_rank_pct, aid_order_day_of_year_nunique_rank_pct,
      aid_last_week_count_rank_pct, aid_last_week_ts_ratio, aid_last_week_day_of_week_mean,
      aid_click_last_week_occurrence_ratio, aid_cart_last_week_occurrence_ratio, aid_order_last_week_occurrence_ratio,
      aid_click_last_week_occurrence_pct_change, aid_cart_last_week_occurrence_pct_change, aid_order_last_week_occurrence_pct_change,
      session_count, session_aid_nunique, session_aid_last, session_type_last, session_day_of_week_last,
      session_aid_count_mean, session_aid_count_min, session_aid_count_max, session_aid_count_last,
      session_aid_type_mean_mean, session_aid_hour_mean_mean,
      session_aid_session_nunique_rank_pct_mean, session_aid_session_nunique_rank_pct_last,
      session_aid_last_week_session_nunique_mean, session_aid_last_week_session_nunique_last
    ]
    target: candidate_labels
    categorical_features: []

model:
  click:
    num_leaves: 128
    learning_rate: 0.1
    bagging_fraction: 0.9
    bagging_freq: 1
    feature_fraction: 0.9
    feature_fraction_bynode: 1
    min_data_in_leaf: 2000
    min_gain_to_split: 0.00001
    lambda_l1: 0.
    lambda_l2: 0.01
    max_bin: 255
    max_depth: -1
    boost_from_average: True
    objective: lambdarank
    metric: mean_average_precision
    eval_at: [20, 50]
    seed: 42
    feature_fraction_seed: 42
    bagging_seed: 42
    drop_seed: 42
    data_random_seed: 42
    boosting_type: gbdt
    verbose: 1
    n_jobs: -1
  cart:
    num_leaves: 128
    learning_rate: 0.05
    bagging_fraction: 0.9
    bagging_freq: 1
    feature_fraction: 0.9
    feature_fraction_bynode: 1
    min_data_in_leaf: 2000
    min_gain_to_split: 0.00001
    lambda_l1: 0.
    lambda_l2: 0.01
    max_bin: 255
    max_depth: -1
    boost_from_average: True
    objective: lambdarank
    metric: mean_average_precision
    eval_at: [20, 50]
    seed: 42
    feature_fraction_seed: 42
    bagging_seed: 42
    drop_seed: 42
    data_random_seed: 42
    boosting_type: gbdt
    verbose: 1
    n_jobs: -1
  order:
    num_leaves: 128
    learning_rate: 0.05
    bagging_fraction: 0.9
    bagging_freq: 1
    feature_fraction: 0.9
    feature_fraction_bynode: 1
    min_data_in_leaf: 2000
    min_gain_to_split: 0.00001
    lambda_l1: 0.
    lambda_l2: 0.01
    max_bin: 255
    max_depth: -1
    boost_from_average: True
    objective: lambdarank
    metric: mean_average_precision
    eval_at: [20, 50]
    seed: 42
    feature_fraction_seed: 42
    bagging_seed: 42
    drop_seed: 42
    data_random_seed: 42
    boosting_type: gbdt
    verbose: 1
    n_jobs: -1

fit:
  click:
    boosting_rounds: 1000
    early_stopping_rounds: 200
  cart:
    boosting_rounds: 1000
    early_stopping_rounds: 200
  order:
    boosting_rounds: 1000
    early_stopping_rounds: 200

persistence:
  save_models: True
  visualize_feature_importance: True
  save_val_predictions: True
  save_test_predictions: True
  visualize_predictions: True
