dataset:
  sampling_strategy: diff
  load_dataset: True
  chunk_size: 30000
  hour_difference: 1
  target_aggregation: mean

model:
  model_class: CollaborativeFiltering
  model_checkpoint_path: null
  n_embeddings: 1855603
  n_factors: 32
  sparse: True
  dropout_probability: 0.

training:
  training_batch_size: 262144
  validation_batch_size: 262144
  scores: True
  loss_function: BCEWithLogitsLoss
  loss_args: {}
  optimizer: SparseAdam
  optimizer_args:
    lr: 0.0005
    betas: [0.9, 0.999]
  lr_scheduler: StepLR
  lr_scheduler_args:
    step_size: 7500
    gamma: 0.5
    last_epoch: -1
  epochs: 250
  early_stopping_patience: 20
  random_state: 42
  deterministic_cudnn: False
  device: cuda

persistence:
  model_directory: aid_collaborative_filtering
  visualize_learning_curve: True
  save_best_model: True
  save_epoch_model: []