dataset:
  pairs: aid
  load_dataset: False
  chunk_size: 1000
  hour_difference: 1
  target_aggregation: mean

model:
  model_class: CollaborativeFiltering
  model_checkpoint_path: null
  embedding_dim: 8

training:
  training_batch_size: 512
  validation_batch_size: 1024
  loss_function: MSELoss
  loss_args: {}
  optimizer: Adam
  optimizer_args:
    lr: 0.01
    betas: [0.9, 0.999]
  lr_scheduler: CosineAnnealingLR
  lr_scheduler_args:
    T_max: 300
    eta_min: 0.000001
    last_epoch: -1
  epochs: 250
  early_stopping_patience: 5
  random_state: 42
  deterministic_cudnn: False
  device: cuda

persistence:
  visualize_learning_curve: True
  save_best_model: True
  save_epoch_model: []